---
title: "Final_Project_Code"
output: pdf_document
date: "2026-04-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
#Import data
df <- read.csv("~/Downloads/background_noise_focus_dataset.csv")
```


```{r pressure, echo=FALSE}
#Exploratory Data Analysis
summary(df)

#i converted all ofthese b/c they're all characters
df$background_noise_type <- as.factor(df$background_noise_type)
df$role <- as.factor(df$role)
df$task_type <- as.factor(df$task_type)

boxplot(perceived_focus_score ~ background_noise_type, data = df, las =2 )

#data is skewed - we may need to mention this
hist(df$perceived_focus_score)

#no outliers, median is 5
boxplot(df$perceived_focus_score)

#this isn't really helpful
plot(df$noise_volume_level,df$perceived_focus_score)

?mean
focus_avg <- aggregate(perceived_focus_score ~ noise_volume_level,
                       data = df, mean)
plot(focus_avg$noise_volume_level, focus_avg$perceived_focus_score, 
     col = "deeppink", xlab = "Noise Volume 1-10", ylab = "Average Focus Score")
abline(lm(perceived_focus_score ~ noise_volume_level, data = df), col = "red")

#CATEGORY: split by type of noise, e.g. instrumental vs. traffic
#Traffic noise type
traffic_df <- subset(df, background_noise_type == "Traffic Noise" )
traffic_avg_focus <- aggregate(perceived_focus_score ~ noise_volume_level,
                             data = traffic_df, mean)

plot(traffic_avg_focus$noise_volume_level, traffic_avg_focus$perceived_focus_score, 
     col = "blue", xlab = "Volume 1-10", ylab = "Average Focus Score Traffic",
     type = "b")
abline(lm(perceived_focus_score ~ noise_volume_level, data = instr_avg_focus), 
       col = "red")

traffic_model <- lm(traffic_avg_focus)
summary(traffic_model)


#Instrumental noise type
instrumental_df <- subset(df, background_noise_type == "Instrumental Music" )
instr_avg_focus <- aggregate(perceived_focus_score ~ noise_volume_level,
                             data = instrumental_df, mean)
plot(instr_avg_focus$noise_volume_level, instr_avg_focus$perceived_focus_score, 
     col = "blue", xlab = "Volume 1-10", ylab = "Average Focus Score Instr",
     type = "b")
abline(lm(perceived_focus_score ~ noise_volume_level, data = instr_avg_focus), 
       col = "red")

#Songs with lyrics noise type
lyrics_df <- subset(df, background_noise_type == "Songs with Lyrics" )
lyrics_avg_focus <- aggregate(perceived_focus_score ~ noise_volume_level,
                             data = lyrics_df, mean)
plot(lyrics_avg_focus$noise_volume_level, lyrics_avg_focus$perceived_focus_score, 
     col = "blue", xlab = "Volume 1-10", ylab = "Average Focus Score Lyrics",
     type = "b")
abline(lm(perceived_focus_score ~ noise_volume_level, data = lyrics_avg_focus), 
       col = "red")

#Silence noise type
silence_df <- subset(df, background_noise_type == "Silence" )
silence_avg_focus <- aggregate(perceived_focus_score ~ noise_volume_level,
                             data = silence_df, mean)
plot(silence_avg_focus$noise_volume_level, silence_avg_focus$perceived_focus_score, 
     col = "blue", xlab = "Volume 1-10", ylab = "Average Focus Score Silence",
     type = "b")
abline(lm(perceived_focus_score ~ noise_volume_level, data = silence_avg_focus), 
       col = "red")


#Cafe background noise type
cafe_df <- subset(df, background_noise_type == "Cafe noise" )
cafe_avg_focus <- aggregate(perceived_focus_score ~ noise_volume_level,
                             data = silence_df, mean)
plot(cafe_avg_focus$noise_volume_level, cafe_avg_focus$perceived_focus_score, 
     col = "blue", xlab = "Volume 1-10", ylab = "Average Focus Score Silence",
     type = "b")
abline(lm(perceived_focus_score ~ noise_volume_level, data = cafe_avg_focus), 
       col = "red")



traffic_model <- lm(traffic_avg_focus)
summary(traffic_model)

```


